name: Create New Issue
on:
  schedule:
    - cron: "20 * * * 3"

jobs:
  create_issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JasonEtco/create-an-issue@v2
        with:
          filename: .github/ISSUE_TEMPLATE/validator_weekly_sync.md
