on: 
  workflow_run:
    workflows: [Create New Issue]
    types:
      - requested
name: pin issue based on label
jobs:
  pinAnIssue:
    name: pin an issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: pin an issue
      uses: bdougie/issue-pin-by-label@v4.0.1

      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LABEL_NAME: "Weekly sync"
